Rsamtools rmd
Bioconductor/Rsamtools pull request #53
Opened 2023-03-15 15:12 UTC by bellatrick

[Rsamtools-Overview.pdf](https://github.com/Bioconductor/Rsamtools/files/10981329/Rsamtools-Overview.pdf)
[HTML](http://rpubs.com/Bellatrick/1015683)

@Bioconductor/sweave2rmd Hello, could you please review my PR for the sweave2rmd conversion.

2023-03-24 19:41 UTC, mcarlsn reviewed
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- [ ] in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [ ] in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ] any added lines use the same spacing and indents as the existing
  document
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the `DESCRIPTION` file; refer to the contribution guide for acceptable
  formats
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, check that the
  `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line
  is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, include=FALSE}
To match the inline code in the [original vignette](https://github.com/Bioconductor/Rsamtools/blob/devel/vignettes/Rsamtools-Overview.Rnw), we should update this line to ```{r, echo=FALSE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
To match the original vignette, we can update line 72 with the chunk name: ```{r ScanBamParam]

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to match the original vignette: ```{r scanBam, keep.source=TRUE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Please update inline code to: ```{r scanBam-elts-1}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Please update inline code to: ```{r scanBam-elts-2}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Please update inline code to: ```{r scanBam-elts-class}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r scanBam-to-IRanges}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r lst-to-DataFrame}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r indexed-file}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Update inline code to ```{r bam-remote, eval=FALSE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r summaryFunction}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r summaryByChromosome}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r,eval=FALSE}
Update inline code to ```{r keggrest, eval = FALSE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r caffeine-kegg}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, message=FALSE}
Update inline code to ```{r txdb-transcripts, message=FALSE]

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +bamRanges <- transcripts(
Why are library(TxDb.Hsapiens.UCSC.hg18.knownGene) and  bamRanges <- transcripts... in separate code chunks? I believe they should be in the same chunk - looking at the [original vignette](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://bioconductor.org/packages/3.17/bioc/vignettes/Rsamtools/inst/doc/Rsamtools-Overview.pdf) - although if there's a reason you've added them to separate ones (e.g., because of the message=FALSE inline code perhaps?) please let me know

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to: ```{r bamRanges-genome}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to: ```{r BamViews-parts]

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r BamViews-construct, keep.source=TRUE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r BamViews-query}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r,eval=FALSE}
Update inline code ```{r bamIndicies,eval=FALSE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Update inline code to ```{r readGAlignments, eval=FALSE]

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, include=FALSE}
Update inline code to ```{r olaps, include=FALSE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```
These two code chunks should be merged together into 1 chunk, per the original vignette: https://github.com/Bioconductor/Rsamtools/blob/devel/vignettes/Rsamtools-Overview.Rnw

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r read-lengths]

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r focal}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r olap-cvg, keep.source=TRUE}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r olap-cvg-as-m}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r}
Update inline code to ```{r sessionInfo}

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +efforts.
Looks like there are a few lines missing here. Please update the text after "e.g.," to the following: 

... e.g., _AlignedRead_ objects in the _ShortRead_ package (for quality assessment and read manipulation), or _GAlignments_ objects in _GenomicAlignments_ package (for RNA-seq and other applications). Those desiring more functionality are encouraged to explore _samtools_ and related software efforts.

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +defined
Please add a single carriage line between "The `bamRanges` 'knows' the genome for which the ranges are defined" and the code chunk below it.

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Add a single carriage line between the line, "and then queries the 1000 genomes project for reads overlapping our transcripts." and the code chunk below it.

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Please add a single carriage line between "all files in an appropriate directory" and the code chunk below.

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Please add an extra single carriage line above this code chunk

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +
You can delete this extra carriage line

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +
You can delete this extra carriage line

2023-03-24 19:41 UTC, mcarlsn commented on vignettes/Rsamtools-Overview.Rmd
> +
You can delete this extra carriage line

2023-03-24 19:52 UTC, bellatrick commented
> Great work @bellatrick. Once you've resolved the comments I left in the script, you'll be able to check mark the following items in the list below. Please let me know if you have any questions!
> 
> * [x]  the `.Rmd` file knits to `HTML`
> * [x]  `R CMD build` runs without errors or timeouts
> * [x]  the tarball from `R CMD build` contains the `HTML` (check with the
>   following by substituting the package name and vignette name `tar ztf package_name.tar.gz | grep 'doc/vignette_name'`)
> * [x]  the `.Rnw` file has been removed
> * [x]  in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
> * [x]  in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
> * [ ]  any added lines use the same spacing and indents as the existing document
> * [x]  if agreed with the Maintainer, the contributor is in the author list in the `DESCRIPTION` file; refer to the contribution guide for acceptable formats
> * [x]  if agreed with the Maintainer, the contributor is in the author list
>   in the vignette's YAML; refer to the contribution guide for acceptable formats
> * [x]  if this pull request includes a conversion from using the separate `Author` and `Maintainer` lines into the `Authors@R` vector, check that the `Authors@R` vector includes the maintainer as specified with `role='cre'`.
> * [x]  if this pull request includes a conversion from using the separate `Author` and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line is completely removed.
> * [ ]  `HTML` document is representative of the `PDF` in content and
>   in general the presentation
> * [ ]  Where the contributor was not able to preserve the content and presentation of the `PDF` is noted as a comment in the pull request
> * [ ]  the R Markdown file is representative of the Sweave document and follows best practices, such as replacing links to Bioconductor packages with calls to BiocStyle's `Biocpkg()`

Thanks for the review, I will make the necessary changes.

2023-03-25 06:03 UTC, bellatrick commented on vignettes/Rsamtools-Overview.Rmd
> +bamRanges <- transcripts(
Yes, I added them in separate chunks because of the message=FALSE code for loading the TxDb.Hsapiens.UCSC.hg18.knownGene library

2023-03-25 07:04 UTC, bellatrick commented
@mcarlsn I have made the requested changes.
Also, I noticed that the URL in line 167 doesn't reflow and goes past the margin in both RStudio and in the HTML file, do you have any suggestions to correct that?

2023-03-28 18:48 UTC, mcarlsn commented
Amazing, thank you @bellatrick! It is okay that the URL extends past the margin. Doing a final pass on the vignette, I noticed that the following text chunks extend past the vertical line: 
- lines 180-203 
- 219-220 
- 229 
- 231
- 235
- 245
- 433
- 492 

Please fix those chunks. Lastly, edit line 57 to say, "Those desiring more functionality are encouraged to explore _samtools_ and related software efforts." Right now, there is no mention of "samtools" in that passage. Once those edits are made, you're good to go!

2023-03-28 19:45 UTC, bellatrick commented
> Amazing, thank you @bellatrick! It is okay that the URL extends past the margin. Doing a final pass on the vignette, I noticed that the following text chunks extend past the vertical line:
> 
> * lines 180-203
> * 219-220
> * 229
> * 231
> * 235
> * 245
> * 433
> * 492
> 
> Please fix those chunks. Lastly, edit line 57 to say, "Those desiring more functionality are encouraged to explore _samtools_ and related software efforts." Right now, there is no mention of "samtools" in that passage. Once those edits are made, you're good to go!

@mcarlsn  Thanks for pointing out all the problematic paragraphs and for your patience. I initially used VScode's terminal to push my changes and I am only now realizing that its editor makes RMD files lose their formatting. I have pushed my update.

2023-03-30 13:56 UTC, mcarlsn commented
> > Amazing, thank you @bellatrick! It is okay that the URL extends past the margin. Doing a final pass on the vignette, I noticed that the following text chunks extend past the vertical line:
> > 
> > * lines 180-203
> > * 219-220
> > * 229
> > * 231
> > * 235
> > * 245
> > * 433
> > * 492
> > 
> > Please fix those chunks. Lastly, edit line 57 to say, "Those desiring more functionality are encouraged to explore _samtools_ and related software efforts." Right now, there is no mention of "samtools" in that passage. Once those edits are made, you're good to go!
> 
> @mcarlsn Thanks for pointing out all the problematic paragraphs and for your patience. I initially used VScode's terminal to push my changes and I am only now realizing that its editor makes RMD files lose their formatting. I have pushed my update.

Wonderful, it looks great! Thanks for all your work on this, @bellatrick.

2023-04-01 03:12 UTC, jwokaty requested changes
@bellatrick, Thanks for this PR. I noticed a few issues that should be resolved before I merge.

2023-04-01 03:12 UTC, jwokaty commented on DESCRIPTION
> +    BSgenome.Hsapiens.UCSC.hg19, RUnit, BiocStyle,knitr
Add a space between `BiocStyle,` and `knitr`

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +- name: "Nathaniel Hayden"
Remove Herve, Valerie, and Nathaniel. Looking at the original PDF, only Martin is listed as the author.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +title: "An introduction to Rsamtools"
Capitalize the `I` in `introduction`.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +  %\VignetteIndexEntry{An introduction to Rsamtools}
Capitalize the `I` in `introduction`.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +*GenomicAlignments* package (for RNA-seq and other applications). Those desiring
ShortRead and GenomicAlignments are Bioconductor packages. Could you use `Biocpkg` to generate their links?

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
This code block should be named `bam-index`

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Add code block name as in .Rnw.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
Add code block name as in .Rnw.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +Biocpkg("GenomicFiles")` package is also useful for iterating through `BAM`
`r Biocpkg("GenomicFiles")`

That's inline code. It must be on 1 line in order to be run as code; otherwise, it will just print the text.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +Biocpkg("Rsamtools")` is as a starting point for creating objects suitable for a
Join the inline code so that it's on 1 line and runs properly.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +*ShortRead*.
Use `Biocpkg()` to create a link to the package.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +with caffeine metabolism. Using the KEGGREST package, the steps are
Use `Biocpkg()` to make a link for the KEGGREST package.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +*GenomicFeatures* vignette). We'll find that the names used for chromosomes in
Use `Biocpkg()` to create links for the biomaRt and GenomicFeatures packages.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +the interface to the integrative genome browser (IGV) in *SRAdb* useful for
Use `Biocpkg()` to make links for GenomicRanges, ShortRead, Biostrings, BSgenome, IRanges, rtracklayer, and SRAdb.

2023-04-01 03:12 UTC, jwokaty commented on vignettes/Rsamtools-Overview.Rmd
> +*RCurl* package to retrieve the names of all files in an
`RCurl` is a CRAN package. Use the following to generate its link

    `r CRANpkg("RCurl")`

2023-04-01 12:33 UTC, bellatrick commented on vignettes/Rsamtools-Overview.Rmd
> +*RCurl* package to retrieve the names of all files in an
@jwokaty thank you so much for the review. I have added the requested changes

2023-04-01 15:14 UTC, bellatrick commented on vignettes/Rsamtools-Overview.Rmd
> +```{r, eval=FALSE}
@jwokaty I noticed that the name for the code chunk here and the one in line 383 in the .Rnw file is exactly the same, so i added an hyphen for this one, is that okay?

2023-04-04 03:31 UTC, merged

2023-04-04 03:31 UTC, jwokaty commented
Thanks for your contribution!